spring:
  datasource:
    url: jdbc:h2:mem:./bookstore
  h2:
    console:
      # Enable web-console
      enabled: true
      path: /h2-console
  jpa:
    # Show generated SQL (false by default)
    show-sql: false
    hibernate:
      # Create and then destroy the schema at the end of the session
      ddl-auto: create-drop
